mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http.response import HttpResponseRedirect

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', lambda r: HttpResponseRedirect('polls/')),
]

polls/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>[0-9]+)/cancel_vote/$', views.cancel_vote, name='cancel_vote'),
    url(r'^(?P<question_id>[0-9]+)/open/$', views.open, name='open'),
    url(r'^(?P<question_id>[0-9]+)/close/$', views.close, name='close'),
    url(r'^(?P<question_id>[0-9]+)/show/$', views.show, name='show'),
    url(r'^(?P<question_id>[0-9]+)/hide/$', views.hide, name='hide'),
    url(r'^(?P<question_id>[0-9]+)/reset/$', views.reset, name='reset'),
    url(r'^(?P<question_id>[0-9]+)/next/$', views.next, name='next'),
    url(r'^(?P<question_id>[0-9]+)/prev/$', views.prev, name='prev'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/polls/login'}, name='logout'),

    url(r'^usergen/$', views.usergen, name='usergen'),
    url(r'^usergen/generate/$', views.usergen_generate, name='usergen_generate'),
]

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Question(models.Model):
    ADVICE = (
        ('positive', 'Overnemen'),
        ('neutral', 'Neutraal'),
        ('na', 'NVT - bestuursamendement'),
        ('negative', 'Niet overnemen'),
    )

    question_text = models.CharField("Titel", max_length=2000)
    question_change = models.CharField("Wijziging", max_length=4000, default="")
    question_people = models.CharField("Indieners", max_length=4000, default="")
    question_category = models.IntegerField("Category", default=2, choices=((1,'1'),(2,'2'),(3,'3')))
    question_advice = models.CharField("Advies Programmacommissie", choices=ADVICE, max_length=4000, default="neutral")

    question_visible = models.BooleanField("Zichtbaar", default=False)
    question_open = models.BooleanField("Open", default=False)
    
    def __str__(self):
        return self.question_text
        
    class Meta:
        verbose_name = 'stemming'
        verbose_name_plural = 'stemmingen'
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField("Tekst",max_length=2000)

    def __str__(self):
        return self.choice_text
        
    class Meta:
        verbose_name = 'keuze'
        verbose_name_plural = 'keuzes'        

class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    
    class Meta:
        # Allow a user to only answer a question once
        unique_together = ('user', 'question',)

    def __str__(self):
        return str(self.user)+": "+str(self.question)+"->"+str(self.choice)

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import re

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError

from django.contrib.auth.models import User
from .models import Question, Answer, Choice

def sort_by_number(x):
    s = ''.join(i for i in x.question_text.split('.')[0] if i.isdigit())
    return ('0' * (3-len(s))) + x.question_text

@login_required
def index(request):
    open_questions = Question.objects.filter(question_visible=True, question_open=True)
    open_not_voted_questions = sorted(open_questions.exclude(answer__user=request.user), key=sort_by_number)
    open_voted_questions = sorted(open_questions.filter(answer__user=request.user), key=sort_by_number)
    closed_questions = sorted(Question.objects.filter(question_visible=True, question_open=False), key=sort_by_number)
    if request.user.is_staff:
        hidden_questions = sorted(Question.objects.filter(question_visible=False), key=sort_by_number)
    else:
        hidden_questions = []
    return render(request, 'polls/index.html', {
                    'open_not_voted_questions': open_not_voted_questions,
                    'open_voted_questions': open_voted_questions,
                    'closed_questions': closed_questions,
                    'hidden_questions': hidden_questions,
                })

class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'question_list'

    def get_queryset(self):
        return Question.objects.filter(question_visible=True)
        
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        for question in context['question_list']:
            question.user_voted = Answer.objects.filter(user=self.request.user,question=question).exists()
        return context        

class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['user_voted'] = Answer.objects.filter(user=self.request.user,question=context['question']).exists()
        return context

class ResultsView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    def get_context_data(self, **kwargs):
        context = super(ResultsView, self).get_context_data(**kwargs)
        context['user_voted'] = Answer.objects.filter(user=self.request.user,question=context['question']).exists()
        return context

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "U dient een keuze te maken",
        })
    if not question.question_open:
        return render(request, 'polls/detail.html', {
                    'question': question,
                    'error_message': "De stemming is gesloten",
                })
    if request.user.is_staff:
        return render(request, 'polls/detail.html', {
                    'question': question,
                    'error_message': "Organisatoren mogen niet stemmen",
                })
    
    # Remove previous answer
    Answer.objects.filter(user=request.user, question=question).delete()
    
    # Add the answer
    a = Answer(user=request.user, question=question, choice=selected_choice)
    a.save()

    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    
@login_required
def cancel_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if not question.question_open:
        return render(request, 'polls/detail.html', {
                    'question': question,
                    'error_message': "De stemming is gesloten",
                })
    # Remove previous answer
    Answer.objects.filter(user=request.user, question=question).delete()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

@login_required
def usergen(request):
    if not request.user.is_superuser:
        return render(request, 'polls/usergen.html', {
                    'error_message': "U bent geen admin",
                })
    return render(request, 'polls/usergen.html')
    
@login_required
def open(request, question_id):
    if not request.user.is_superuser:
        return render(request, 'polls/results.html', {
                    'error_message': "U bent geen admin",
                })
    question = get_object_or_404(Question, pk=question_id)
    question.question_open = True
    question.question_visible = True
    question.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    
@login_required
def close(request, question_id):
    if not request.user.is_superuser:
        return render(request, 'polls/results.html', {
                    'error_message': "U bent geen admin",
                })
    question = get_object_or_404(Question, pk=question_id)
    question.question_open = False
    question.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    
@login_required
def show(request, question_id):
    if not request.user.is_superuser:
        return render(request, 'polls/results.html', {
                    'error_message': "U bent geen admin",
                })
    question = get_object_or_404(Question, pk=question_id)
    question.question_visible = True
    question.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    
@login_required
def hide(request, question_id):
    if not request.user.is_superuser:
        return render(request, 'polls/results.html', {
                    'error_message': "U bent geen admin",
                })
    question = get_object_or_404(Question, pk=question_id)
    question.question_visible = False
    question.question_open = False
    question.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

@login_required
def next(request, question_id):
    if not request.user.is_superuser:
        return render(request, 'polls/results.html', {
                    'error_message': "U bent geen admin",
                })
    question = get_object_or_404(Question, pk=question_id)
    qs = sorted(Question.objects.filter(question_category__in=[2,3]), key=sort_by_number)
    for i in range(0, len(qs)):
        if str(qs[i].id) == str(question_id) and i+1 < len(qs):
            return HttpResponseRedirect(reverse('polls:results', args=(qs[i+1].id,)))
    return HttpResponseRedirect(reverse('polls:index'))
    
@login_required
def prev(request, question_id):
    if not request.user.is_superuser:
        return render(request, 'polls/results.html', {
                    'error_message': "U bent geen admin",
                })
    question = get_object_or_404(Question, pk=question_id)
    qs = sorted(Question.objects.filter(question_category__in=[2,3]), key=sort_by_number)
    for i in range(0, len(qs)):
        if str(qs[i].id) == str(question_id) and i-1 >= 0:
            return HttpResponseRedirect(reverse('polls:results', args=(qs[i-1].id,)))
    return HttpResponseRedirect(reverse('polls:index'))

@login_required
def reset(request, question_id):
    if not request.user.is_superuser:
        return render(request, 'polls/results.html', {
                    'error_message': "U bent geen admin",
                })
    question = get_object_or_404(Question, pk=question_id)
    Answer.objects.filter(question=question).delete()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

@login_required
def usergen_generate(request):
    if not request.user.is_superuser:
        return render(request, 'polls/usergen.html', {
                    'error_message': "U bent geen admin",
                })
    # See what the highest "voter id" is
    highest = 0
    for user in User.objects.all():
        try:
            value = int(user.username)
            if value > highest:
                highest = value
        except (ValueError):
            pass
            
    count=int(request.POST['count'])
    result = []
    for i in range(highest+1, highest+1+count):
        username=str(i)
        password = User.objects.make_random_password(length=12, allowed_chars="0123456789")
        u = User.objects.create_user(username=username, password=password)
        password = re.sub(r"([0-9][0-9][0-9])", r"\1 ", password)
        result.append({"username":username,"password":password})
    
    return render(request, 'polls/usergen_result.html', {
                'users': result
            })

polls/templates/polls/detail.html
{% extends "base.html" %}

{% block content %}
    <ol class="breadcrumb">
      <li><a href="{% url 'polls:index' %}">Overzicht</a></li>
      <li class="active">Stemmen</li>
    </ol>            

    <p>
        <em>Amendement:</em><br>
        <strong>{{ question.question_text }}</strong>
    </p>

    {% if error_message %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ error_message }}</strong>
        </div>
    {% endif %}
    
    {% if user_voted %}
        <div class="alert alert-info" role="alert">
            <strong>U heeft al gestemd.</strong>
            <a href="{% url 'polls:results' question.id %}" class="btn btn-primary">Naar resultaten</a>
            <br>
        </div>
    {% endif %}

    <em>Maak uw keuze:</em>
    <form action="{% url 'polls:vote' question.id %}" method="post" class="form">
        {% csrf_token %}
        <div style="width:100%;font-size:150%;">
            {% for choice in question.choice_set.all %}
                <label class="btn btn-default btn-block">
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    {{ choice.choice_text }}
                </label>
            {% endfor %}
        </div>
        <input type="submit" value="Stem uitbrengen" class="btn btn-lg btn-danger btn-block" style="margin-top:1em;"/>
    </form>
    <br>
    <a href="{% url 'polls:cancel_vote' question.id %}" class="btn btn-default btn-block">Ik onthoud mij van stemmen</a>
    <p><br><em>U kunt tot de stemming sluit zo vaak als u wilt een stem uitbrengen. Deze vervangt steeds uw vorige stem.</em></p>
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}

{% block head %}
        {% if not request.user.is_staff %}
            <script>
                setTimeout(function(){ window.location = window.location; }, 10000);
            </script>
        {% endif %}
{% endblock %}

{% block content %}
    <ol class="breadcrumb">
      <li class="active">Overzicht</li>
    </ol>
    {% if request.user.is_superuser %}
        <div class="alert alert-info" role="alert">
            <strong>Ingelogd als superuser</strong>
        </div>
        <h2>Beheer</h2>
        <a class="btn btn-default btn-block" href="/admin/">Beheersysteem</a>
        <a class="btn btn-default btn-block" href="{% url 'polls:usergen' %}">Logins aanmaken</a>
    {% else %}
        {% if request.user.is_staff %}
            <div class="alert alert-info" role="alert">
                <strong>Ingelogd als organisator</strong>
            </div>
        {% endif %}
    {% endif %}
    {% if open_not_voted_questions %}
        <h2>Stemmen</h2>
        {% for question in open_not_voted_questions %}
            {% if request.user.is_staff %}
                <a class="btn btn-default btn-block" href="{% url 'polls:results' question.id %}">{{ question.question_text }}</a>
            {% else %}
                <a class="btn btn-primary btn-block" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
            {% endif %}
        {% endfor %}
    {% endif %}
    <br/><a href="/polls" class="btn btn-default btn-block">Verversen</span></a>

    {% if open_voted_questions %}
        <h2>Reeds gestemd</h2>
        {% for question in open_voted_questions %}
            <a class="btn btn-default btn-block" href="{% url 'polls:results' question.id %}">{{ question.question_text }}</a>
        {% endfor %}
    {% endif %}
    {% if closed_questions %}
    <h2>Gesloten stemmingen</h2>
        {% for question in closed_questions %}
            <a class="btn btn-default btn-block" href="{% url 'polls:results' question.id %}">{{ question.question_text }}</a>
        {% endfor %}
    {% endif %}
    {% if hidden_questions %}
    <h2>Onzichtbare stemmingen</h2>
        {% for question in hidden_questions %}
            <a class="btn btn-default btn-block" href="{% url 'polls:results' question.id %}">{{ question.question_text }}</a>
        {% endfor %}
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}

{% block head %}
    {% if question.question_open %}
        <script>
            setTimeout(function(){ window.location = window.location; }, 10000);
        </script>
    {% endif %}
{% endblock %}

{% block content %}
    {% if request.user.is_staff %}
        <head>
            <style>
.container {
  max-width: 100%;
  width: 100%;
  font-size: 300%;
  padding-left: 1em;
  padding-right: 1em;
}
.breadcrumb {
    font-size: 33%;
}
            </style>
        </head>
    {% endif %}
    <ol class="breadcrumb">
      <li><a href="{% url 'polls:index' %}">Overzicht</a></li>
        {% if question.question_open and not request.user.is_staff %}
            <li><a href="{% url 'polls:detail' question.id %}">Stemmen</a></li>
        {% else %}
            <li>Stemmen</li>
        {% endif %}
      <li class="active">Resultaten</li>
    </ol>            
    
    {% if request.user.is_staff %}
        <p style="float:right;"><a href="{% url 'polls:prev' question.id %}" class="btn btn-default">Vorige</a>
        <a href="{% url 'polls:next' question.id %}" class="btn btn-default">Volgende</a></p>
    {% endif %}

    <p>
        <strong>{{ question.question_text }}</strong>
        {% if request.user.is_staff %}
            - Categorie {{ question.question_category }},

            Advies:
            {% if question.question_advice == 'negative' %}
                <span style="color:darkred;">Niet overnemen</span>
            {% endif %}
            {% if question.question_advice == 'neutral' %}
                Neutraal
            {% endif %}
            {% if question.question_advice == 'positive' %}
                <span style="color:green;">Overnemen</span>
            {% endif %}        
            {% if question.question_advice == 'na' %}
                NVT - bestuursamendement
            {% endif %}        
        {% endif %}        
    </p>
    {% if request.user.is_staff %}
        <p style="background: white;padding:0.4em;">
            {{ question.question_change|linebreaksbr }}
        </p>    
        <p>
            <span style="font-size:70%;"><em>Indieners:</em>
            {{ question.question_people }}</span>
        </p>    
    {% endif %}
    {% if question.question_open %}
        {% if not request.user.is_staff %}
            {% if user_voted %}
                <div class="alert alert-success" role="alert">
                    <strong>U heeft gestemd.</strong>
                    <a href="{% url 'polls:detail' question.id %}" class="btn btn-warning">Stem aanpassen</a>
                </div>
            {% else %}
                <div class="alert alert-danger" role="alert"><strong>U heeft niet gestemd.</strong>
                    <a href="{% url 'polls:detail' question.id %}" class="btn btn-danger">Stemmen</a>
                </div>
            {% endif %}
        {% endif %}        

        <p>
            De stemming staat op dit moment open.
        </p>
        
        <p>
            <table class="table">
                <tr><th>Keuze</th><th>Stemmen</th></tr>
                {% for choice in question.choice_set.all %}
                    <tr><td>{{ choice.choice_text }}</td><td><em>...</em></td></tr>
                {% endfor %}
            </table>
        </p>        
    {% else %}
        {% if not request.user.is_staff %}
            {% if user_voted %}
                <div class="alert alert-success" role="alert">
                    <strong>U heeft gestemd.</strong>
                </div>
            {% else %}
                <div class="alert alert-danger" role="alert"><strong>U heeft niet gestemd.</strong>
                </div>
            {% endif %}
        {% endif %}      
        <table class="table">
            <tr><th>Keuze</th><th>Stemmen</th></tr>
            {% for choice in question.choice_set.all %}
                <tr><td>{{ choice.choice_text }}</td><td>{{ choice.answer_set.count }}</td></tr>
            {% endfor %}
        </table>
    {% endif %}
    <p>Aantal uitgebrachte stemmen: {{ question.answer_set.count }}</p>
    <p><a href="{% url 'polls:index' %}" class="btn btn-primary btn-block">Terug naar overzicht</a></p>
    {% if request.user.is_staff and question.question_open%}
        <p><a href="{% url 'polls:close' question.id %}" class="btn btn-default btn-block">Sluit de stemming</a></p>
    {% endif %}
    {% if request.user.is_staff and not question.question_open%}
        <p><a href="{% url 'polls:open' question.id %}" class="btn btn-default btn-block">Open de stemming</a></p>
    {% endif %}
    {% if request.user.is_staff and not question.question_open%}
        <p><a href="{% url 'polls:hide' question.id %}" class="btn btn-default btn-block">Verberg de stemming</a></p>
    {% endif %}
    {% if request.user.is_staff and not question.question_open%}
        <p><a href="{% url 'polls:reset' question.id %}" class="btn btn-default btn-block">Reset de stemming</a></p>
    {% endif %}
{% endblock %}

polls/templates/polls/usergen.html
{% extends "base.html" %}

{% block content %}
    <ol class="breadcrumb">
      <li><a href="{% url 'polls:index' %}">Overzicht</a></li>
      <li class="active">Logins aanmaken</li>
    </ol>            

    {% if error_message %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ error_message }}</strong>
        </div>
    {% endif %}

    <h2>Logins aanmaken</h2>
    <p>U kunt hier logins aanmaken. Op de resultaatpagina kunt u de lijst met gebruikersnamen en wachtwoorden bekijken.</p>
    <form action="{% url 'polls:usergen_generate' %}" method="post">
    {% csrf_token %}
    <input class="form-control" type="text" name="count" id="count" value="1" placeholder="Aantal" />
    <label class="sr-only" for="count">aantal</label><br />
    <input class="btn btn-lg btn-primary btn-block" type="submit" value="Aanmaken" />
    </form>
{% endblock %}

polls/templates/polls/usergen_result.html
{% extends "base.html" %}

{% block content %}
    <ol class="breadcrumb">
      <li><a href="{% url 'polls:index' %}">Overzicht</a></li>
      <li><a href="{% url 'polls:usergen' %}">Logins aanmaken</a></li>
      <li class="active">Resultaat</li>
    </ol>
    {% if error_message %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ error_message }}</strong>
        </div>
    {% endif %}

    <h2>Aangemaakte logins</h2>
    <table class="table">
        <tr><th>Gebruikersnaam</th><th>Wachtwoord</th></tr>
        {% for u in users %}
            <tr><td>{{ u.username }}</td><td>{{ u.password }}</td></tr>
        {% endfor %}
    </table>
    <a class="btn btn-primary btn-block" href="{% url 'polls:usergen' %}">Klaar</a>
{% endblock %}